PHYSICS_MATERIALS = ({'Name': 'Default',
  'Density': 1000,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'None', 'Density': 1, 'staticFriction': 1.0, 'dynamicFriction': 1.0, 'restitution': 1.0},
 {'Name': 'meatbag.physmat',
  'Density': 1040,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.2},
 {'Name': 'linoleum.physmat',
  'Density': 1200,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'trash.physmat',
  'Density': 481,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'plastic.physmat',
  'Density': 1150,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Medium',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'character_armor.physmat',
  'Density': 7820,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Never',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'furniture_upholstery.physmat',
  'Density': 20,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Heavy',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'metal_transparent.physmat',
  'Density': 7820,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'Transparent',
           'playerVisibility': 'Transparent',
           'projectilePenetration': 'Any',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'tire_car.physmat',
  'Density': 1100,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'meat.physmat',
  'Density': 1040,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Heavy',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'metal_car_pipe_steam.physmat',
  'Density': 7200,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'character_flesh.physmat',
  'Density': 2000,
  'frictionMode': 'Enabled',
  'dynamicFriction': 5,
  'staticFriction': 0.100000001,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'brick.physmat',
  'Density': 2150,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'character_flesh_head.physmat',
  'Density': 1000,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.400000006,
  'staticFriction': 0.00999999978,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'leaves.physmat',
  'Density': 1000,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Any',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'flesh.physmat',
  'Density': 1000,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Heavy',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'water.physmat',
  'Density': 1000,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Any',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'plastic_road.physmat',
  'Density': 1000,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'metal_hollow.physmat',
  'Density': 700,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'cyberware_flesh.physmat',
  'Density': 1000,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'plaster.physmat',
  'Density': 850,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'plexiglass.physmat',
  'Density': 1180,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Medium',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'character_vr.physmat',
  'Density': 1000,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'vehicle_chassis.physmat',
  'Density': 500,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.200000003,
  'staticFriction': 0.219999999,
  'tags': {'aiVisibility': 'SemiTransparent',
           'playerVisibility': 'SemiTransparent',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.0500000007},
 {'Name': 'sand.physmat',
  'Density': 1500,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Gravel'},
  'restitution': 0.200000003},
 {'Name': 'glass_electronics.physmat',
  'Density': 2600,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'leaves_stealth.physmat',
  'Density': 1000,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'Ignore',
           'projectilePenetration': 'Any',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'tarmac.physmat',
  'Density': 2360,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'metal_car.physmat',
  'Density': 2700,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'tiles.physmat',
  'Density': 200,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Never',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'glass_car.physmat',
  'Density': 2500,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'SemiTransparent',
           'playerVisibility': 'SemiTransparent',
           'projectilePenetration': 'Any',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'grass.physmat',
  'Density': 1000,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'concrete.physmat',
  'Density': 2300,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'carpet_techpiercable.physmat',
  'Density': 1314,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'wood_hedge.physmat',
  'Density': 800,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Any',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'stone.physmat',
  'Density': 2500,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'leaves_semitransparent.physmat',
  'Density': 1000,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'SemiTransparent',
           'playerVisibility': 'Ignore',
           'projectilePenetration': 'Any',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'metal_catwalk.physmat',
  'Density': 7200,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'upholstery_car.physmat',
  'Density': 20,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Heavy',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'cyberware_metal.physmat',
  'Density': 1000,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'paper.physmat',
  'Density': 900,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Any',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'leather.physmat',
  'Density': 1000,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Heavy',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'metal_pipe_steam.physmat',
  'Density': 7200,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'metal_pipe_water.physmat',
  'Density': 7200,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'metal_semitransparent.physmat',
  'Density': 7820,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'SemiTransparent',
           'playerVisibility': 'SemiTransparent',
           'projectilePenetration': 'Any',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'neon.physmat',
  'Density': 2600,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'Transparent',
           'playerVisibility': 'Transparent',
           'projectilePenetration': 'Any',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'glass_dst.physmat',
  'Density': 2600,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'Transparent',
           'playerVisibility': 'Transparent',
           'projectilePenetration': 'Any',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'plastic_car.physmat',
  'Density': 1150,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Medium',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'mud.physmat',
  'Density': 2100,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Gravel'},
  'restitution': 0.200000003},
 {'Name': 'dirt.physmat',
  'Density': 1500,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Gravel'},
  'restitution': 0.200000003},
 {'Name': 'metal_car_pipe_water.physmat',
  'Density': 7200,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'furniture_leather.physmat',
  'Density': 860,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'asphalt.physmat',
  'Density': 2243,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'wood_bamboo_poles.physmat',
  'Density': 800,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Any',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'glass_opaque.physmat',
  'Density': 2600,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Never',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'carpet.physmat',
  'Density': 1314,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Medium',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'food.physmat',
  'Density': 1040,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Any',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'cyberware_metal_head.physmat',
  'Density': 1000,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'metal_road.physmat',
  'Density': 7200,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'wood_tree.physmat',
  'Density': 800,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Heavy',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'wood_player_npc_semitransparent.physmat',
  'Density': 800,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'SemiTransparent',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'wood.physmat',
  'Density': 800,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'metal_car_ricochet.physmat',
  'Density': 2700,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Always',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'cardboard.physmat',
  'Density': 689,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.400000006,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Medium',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'wood_crown.physmat',
  'Density': 800,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Any',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'metal_ricochet.physmat',
  'Density': 7820,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Never',
           'projectileRicochet': 'Always',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'plastic_electronics.physmat',
  'Density': 1070,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'glass_semitransparent.physmat',
  'Density': 2600,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'SemiTransparent',
           'playerVisibility': 'SemiTransparent',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'metal_painted.physmat',
  'Density': 7200,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'rubber.physmat',
  'Density': 1100,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'ceramic.physmat',
  'Density': 2130,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'glass_bulletproof.physmat',
  'Density': 2600,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'Transparent',
           'playerVisibility': 'Transparent',
           'projectilePenetration': 'Never',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'metal_car_electronics.physmat',
  'Density': 2700,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'trash_bag.physmat',
  'Density': 100,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'character_cyberflesh.physmat',
  'Density': 1000,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Heavy',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'metal_heavypiercable.physmat',
  'Density': 7820,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Heavy',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'metal.physmat',
  'Density': 7820,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Never',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'plastic_car_electronics.physmat',
  'Density': 1150,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Medium',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'oil_spill.physmat',
  'Density': 1000,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Any',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'fabrics.physmat',
  'Density': 1150,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'glass.physmat',
  'Density': 2600,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'Transparent',
           'playerVisibility': 'Transparent',
           'projectilePenetration': 'Any',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'metal_techpiercable.physmat',
  'Density': 7820,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'concrete_water_puddles.physmat',
  'Density': 2300,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'TechOnly',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003},
 {'Name': 'character_metal.physmat',
  'Density': 7820,
  'frictionMode': 'Enabled',
  'dynamicFriction': 0.300000012,
  'staticFriction': 0.5,
  'tags': {'aiVisibility': 'None',
           'playerVisibility': 'None',
           'projectilePenetration': 'Never',
           'projectileRicochet': 'Default',
           'vehicleTraction': 'Default'},
  'restitution': 0.200000003})

PHYSICS_MATERIALS_BY_NAME = {material["Name"]: material for material in PHYSICS_MATERIALS}
PHYSICS_MATERIAL_ENUM_NAMES = tuple(material["Name"] for material in PHYSICS_MATERIALS)


def physmat_list():
    return PHYSICS_MATERIALS


def get_physics_material(name, default="Default"):
    return PHYSICS_MATERIALS_BY_NAME.get(name, PHYSICS_MATERIALS_BY_NAME[default])


def physics_material_enum_items():
    return [(name, name, "") for name in PHYSICS_MATERIAL_ENUM_NAMES]
