from .context import (
    DeformationDataError,
    FoliageResourceError,
    SectorContentError,
    SectorExecutionContext,
    SectorInvariantError,
    SectorNodeContext,
    SectorPlacementOperations,
)
from .model import (
    ImportDependency,
    NodeCategory,
    ParsedSector,
    PlannedSector,
    SectorInstance,
    SectorNode,
    SectorNodePlan,
    SectorResourceRef,
)
from .options import (
    MESH_GLB_EXTENSIONS,
    OPTIONAL_SECTOR_INDEX_EXTENSIONS,
    OPTIONAL_SECTOR_NODE_TYPES,
    SECTOR_INDEX_EXTENSIONS,
    SectorImportOptions,
)
from .parser import parse_sector_document
from .planner import compile_sector_plan
from .registry import (
    NODE_HANDLERS,
    SectorNodeHandlerRegistry,
    register_dependency_handler,
    register_node_handler,
    register_placement_handler,
)

_RUNTIME_EXPORTS = frozenset({
    "PrimitiveMeshService",
    "IndexedResourceResolution",
    "IndexedResourceResolver",
    "GIResourceService",
    "GIResourceResult",
    "GIPlacement",
    "GI_PLACEMENT_CONTRACT",
    "CollisionMetadataService",
    "CollisionMetadataPlacement",
    "COLLISION_METADATA_CONTRACTS",
    "SplineService",
    "SplinePointRecord",
    "SplinePlacement",
    "SplineAnalysis",
    "SPLINE_PLACEMENT_CONTRACTS",
    "SemanticResourceResult",
    "SemanticPlacement",
    "SemanticMarkerSpec",
    "SemanticMarkerService",
    "SEMANTIC_MARKER_SPECS",
    "SEMANTIC_MARKER_CONTRACTS",
    "MinimapResourceService",
    "MinimapResourceResult",
    "MinimapPlacement",
    "MinimapBounds",
    "MINIMAP_PLACEMENT_CONTRACT",
    "AcousticSectorService",
    "AcousticResourceResult",
    "AcousticPlacement",
    "ACOUSTIC_PLACEMENT_CONTRACT",
    "EffectResourceService",
    "EffectResourceResult",
    "EffectPlacement",
    "EFFECT_PLACEMENT_CONTRACT",
    "ReflectionProbeService",
    "ReflectionProbeResult",
    "StaticLightingService",
    "StaticLightResult",
    "STATIC_LIGHT_PLACEMENT_CONTRACT",
    "REFLECTION_PROBE_PLACEMENT_CONTRACT",
    "LIGHT_ENERGY_CONTRACT",
    "DIRECTIONAL_LIGHT_AXIS_CONTRACT",
    "DecalService",
    "DecalPlacement",
    "DecalMaterialResult",
    "DECAL_PLACEMENT_CONTRACT",
    "OUTLINE_NODE_TYPES",
    "OUTLINE_COLORS",
    "WORLD_METADATA_CONTRACTS",
    "WorldMetadataService",
    "DeformationService",
    "DeformationPlacement",
    "DeformationFrameMetrics",
    "DeformationAxisContract",
    "DeformationAnalysis",
    "DEFORMATION_CONTRACT",
    "DEFORMATION_AXIS_CONTRACTS",
    "EntityMasterResult",
    "FoliagePopulationSelection",
    "FoliageResourceData",
    "FoliageResourceError",
    "FoliageResourceService",
    "MasterAssetError",
    "MasterAssetServices",
    "MeshMasterPreparation",
    "TransformBufferService",
    "TransformBufferSlice",
    "SectorContentError",
    "SectorExecutionContext",
    "SectorFileSet",
    "SectorInvariantError",
    "SectorImportCaches",
    "SectorImportSession",
})


def __getattr__(name):
    if name not in _RUNTIME_EXPORTS:
        raise AttributeError(name)
    if name.startswith("Sector"):
        from . import session as module
    else:
        from . import services as module
    value = getattr(module, name)
    globals()[name] = value
    return value


__all__ = (
    "PrimitiveMeshService",
    "IndexedResourceResolver",
    "IndexedResourceResolution",
    "COLLISION_METADATA_CONTRACTS",
    "CollisionMetadataPlacement",
    "CollisionMetadataService",
    "GI_PLACEMENT_CONTRACT",
    "GIPlacement",
    "GIResourceResult",
    "GIResourceService",
    "SPLINE_PLACEMENT_CONTRACTS",
    "SplineAnalysis",
    "SplinePlacement",
    "SplinePointRecord",
    "SplineService",
    "SEMANTIC_MARKER_CONTRACTS",
    "SEMANTIC_MARKER_SPECS",
    "SemanticMarkerService",
    "SemanticMarkerSpec",
    "SemanticPlacement",
    "SemanticResourceResult",
    "ACOUSTIC_PLACEMENT_CONTRACT",
    "AcousticPlacement",
    "AcousticResourceResult",
    "AcousticSectorService",
    "MINIMAP_PLACEMENT_CONTRACT",
    "MinimapBounds",
    "MinimapPlacement",
    "MinimapResourceResult",
    "MinimapResourceService",
    "EFFECT_PLACEMENT_CONTRACT",
    "EffectPlacement",
    "EffectResourceResult",
    "EffectResourceService",
    "DIRECTIONAL_LIGHT_AXIS_CONTRACT",
    "LIGHT_ENERGY_CONTRACT",
    "REFLECTION_PROBE_PLACEMENT_CONTRACT",
    "STATIC_LIGHT_PLACEMENT_CONTRACT",
    "StaticLightResult",
    "StaticLightingService",
    "ReflectionProbeResult",
    "ReflectionProbeService",
    "DECAL_PLACEMENT_CONTRACT",
    "DecalMaterialResult",
    "DecalPlacement",
    "DecalService",
    "WorldMetadataService",
    "WORLD_METADATA_CONTRACTS",
    "OUTLINE_COLORS",
    "OUTLINE_NODE_TYPES",
    "DEFORMATION_AXIS_CONTRACTS",
    "DEFORMATION_CONTRACT",
    "DeformationAnalysis",
    "DeformationAxisContract",
    "DeformationDataError",
    "DeformationFrameMetrics",
    "DeformationPlacement",
    "DeformationService",
    "EntityMasterResult",
    "FoliagePopulationSelection",
    "FoliageResourceData",
    "FoliageResourceError",
    "FoliageResourceService",
    "ImportDependency",
    "MasterAssetError",
    "MasterAssetServices",
    "MeshMasterPreparation",
    "MESH_GLB_EXTENSIONS",
    "TransformBufferService",
    "TransformBufferSlice",
    "NODE_HANDLERS",
    "NodeCategory",
    "OPTIONAL_SECTOR_INDEX_EXTENSIONS",
    "OPTIONAL_SECTOR_NODE_TYPES",
    "ParsedSector",
    "PlannedSector",
    "SECTOR_INDEX_EXTENSIONS",
    "SectorFileSet",
    "SectorImportCaches",
    "SectorImportOptions",
    "SectorImportSession",
    "SectorInstance",
    "SectorNode",
    "SectorNodeContext",
    "SectorNodeHandlerRegistry",
    "SectorNodePlan",
    "SectorPlacementOperations",
    "SectorResourceRef",
    "compile_sector_plan",
    "parse_sector_document",
    "register_dependency_handler",
    "register_node_handler",
    "register_placement_handler",
)
