from __future__ import annotations

import numpy as np

RIG_SPACE_CONTRACT_CURRENT = "CP77_RE_MODEL_BL_BONE_X_NEGZ_Y_Y_Z_X_V1"
RIG_SPACE_CONTRACT_DIRECT = "CP77_RE_MODEL_BL_BONE_DIRECT_V1"
EDITOR_SPACE_CONTRACT = "CP77_REDENGINE_WORLD_MODEL_BONE_LOCAL_V1"
SOURCE_REST_SPACE_CONTRACT = "CP77_GLTF_SOURCE_RELATIVE_BLENDER_V1"

GLTF_TO_RED = np.array((
    (1.0, 0.0, 0.0, 0.0),
    (0.0, 0.0, -1.0, 0.0),
    (0.0, 1.0, 0.0, 0.0),
    (0.0, 0.0, 0.0, 1.0),
), dtype=np.float64)
RED_TO_GLTF = np.linalg.inv(GLTF_TO_RED)
RED_TO_BLENDER_BONE_RIGHT = np.array((
    (0.0, 0.0, 1.0, 0.0),
    (0.0, 1.0, 0.0, 0.0),
    (-1.0, 0.0, 0.0, 0.0),
    (0.0, 0.0, 0.0, 1.0),
), dtype=np.float64)
RED_LOCAL_TO_BLENDER_BONE_CURRENT = RED_TO_BLENDER_BONE_RIGHT.T.copy()
BLENDER_BONE_LOCAL_TO_RED_CURRENT = RED_TO_BLENDER_BONE_RIGHT.copy()
GLTF_TO_BLENDER_BONE_RIGHT = RED_TO_GLTF @ RED_TO_BLENDER_BONE_RIGHT
BLENDER_BONE_RIGHT_TO_GLTF = np.linalg.inv(GLTF_TO_BLENDER_BONE_RIGHT)
