from __future__ import annotations

WEIGHT_THRESHOLD = 0.001

ENV_FACE_ENVELOPE = 0
ENV_UPPER_FACE = 1
ENV_LOWER_FACE = 2
ENV_ANTI_STRETCH = 3
ENV_LIPSYNC = 4
ENV_LIPSYNC_LEFT = 5
ENV_LIPSYNC_RIGHT = 6
ENV_JALI_JAW = 7
ENV_JALI_LIPS = 8
ENV_MUZZLE_LIPS = 9
ENV_MUZZLE_EYES = 10
ENV_MUZZLE_BROWS = 11
ENV_MUZZLE_EYE_DIR = 12

INFLUENCE_LINEAR = 0
INFLUENCE_EXPONENTIAL = 1
INFLUENCE_ORGANIC = 2

LIPSYNC_POSE_SUFFIX = "LipsyncPoseOutput"
ANIM_OVERRIDE_SUFFIX = "AnimOverrideWeight"
