from .dynamics import clamp_damping_vectors, damping_force
from .geometry import closest_point_on_segment, closest_point_on_segment_single, orthogonal_vector
from .hierarchy import (
    children_by_parent,
    descendant_indices,
    local_matrices_to_model,
    local_transform_pairs_to_model,
    model_matrices_to_local,
    model_transform_pairs_to_local,
    parent_first_order,
)
from .quaternion import (
    identity_wxyz,
    identity_xyzw,
    matrix_from_xyzw,
    multiply_wxyz,
    multiply_xyzw,
    nlerp_xyzw,
    normalize_sequence_xyzw,
    normalize_wxyz,
    normalize_xyzw,
    slerp_xyzw,
    wxyz_from_matrices,
    xyzw_from_matrices,
)
from .scalar import (
    clamp,
    clamp_scalar,
    lerp,
    limit_weight,
    limit_weight_scalar,
    sin_squared_ease,
    smoothstep,
    wrinkle_weight,
)
from .trs import compose_matrix, compose_matrices, decompose_matrices, interpolate_matrices

__all__ = [
    "children_by_parent",
    "clamp",
    "clamp_damping_vectors",
    "clamp_scalar",
    "closest_point_on_segment",
    "closest_point_on_segment_single",
    "compose_matrix",
    "compose_matrices",
    "damping_force",
    "decompose_matrices",
    "descendant_indices",
    "identity_wxyz",
    "identity_xyzw",
    "interpolate_matrices",
    "lerp",
    "limit_weight",
    "limit_weight_scalar",
    "local_matrices_to_model",
    "local_transform_pairs_to_model",
    "matrix_from_xyzw",
    "model_matrices_to_local",
    "model_transform_pairs_to_local",
    "multiply_wxyz",
    "multiply_xyzw",
    "nlerp_xyzw",
    "normalize_sequence_xyzw",
    "normalize_wxyz",
    "normalize_xyzw",
    "orthogonal_vector",
    "parent_first_order",
    "sin_squared_ease",
    "slerp_xyzw",
    "smoothstep",
    "wrinkle_weight",
    "wxyz_from_matrices",
    "xyzw_from_matrices",
]
